name: Deploy to Vercel and Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' 

      - name: Install frontend dependencies
        working-directory: client
        run: |
          npm install
          npm run build

      - name: Deploy frontend to Vercel
        working-directory: client
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          npx vercel --prod --confirm --scope marialbovin

      - name: Install backend dependencies
        working-directory: server
        run: |
          npm install

      - name: Deploy backend to Firebase
        working-directory: server
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          npx firebase deploy --only functions
